(ns com.jd.bdp.magpie.bootstrap)

(use 'clojure.set) 

(def NIMBUS-THRIFT-PORT "nimbus.thrift.port")
(def MAGPIE-ZOOKEEPER-SERVERS "magpie.zookeeper.servers")
(def MAGPIE-ZOOKEEPER-PORT "magpie.zookeeper.port")
(def MAGPIE-ZOOKEEPER-ROOT "magpie.zookeeper.root")
(def MAGPIE-ZOOKEEPER-CONNECTION-TIMEOUT "magpie.zookeeper.connection.timeout.millis")
(def MAGPIE-ZOOKEEPER-SESSION-TIMEOUT "magpie.zookeeper.session.timeout.millis")
(def MAGPIE-ZOOKEEPER-RETRY-INTERVAL "magpie.zookeeper.retry.interval.millis")
(def MAGPIE-ZOOKEEPER-RETRY-TIMES "magpie.zookeeper.retry.times")
(def MAGPIE-ZOOKEEPER-RETRY-INTERVAL-CEILING "magpie.zookeeper.retry.intervalceiling.millis")
(def MAGPIE-ZOOKEEPER-AUTH-SCHEME "magpie.zookeeper.auth.scheme")
(def MAGPIE-ZOOKEEPER-AUTH-PAYLOAD "magpie.zookeeper.auth.payload")

(def MAGPIE-FLOOR-SCORE "magpie.floor.score")
(def MAGPIE-JARS-DIR "magpie.jars.dir")
(def MAGPIE-PIDS-DIR "magpie.pids.dir")
(def MAGPIE-LOGS-DIR "magpie.logs.dir")
(def MAGPIE-HEARTBEAT-INTERVAL "magpie.heartbeat.interval.millis")
(def MAGPIE-HEALTHCHECK-INTERVAL "magpie.healthcheck.interval.millis")
(def MAGPIE-SCHEDULE-INTERVAL "magpie.schedule.interval.millis")
(def MAGPIE-SCHEDULE-TIMEOUT "magpie.schedule.timeout.millis")
(def MAGPIE-SCHEDULE-LAUNCHWORKER-TIMEOUT "magpie.schedule.launchworker.timeout.millis")
(def MAGPIE-NET-BANDWIDTH-CALCULATE-INTERVAL "magpie.net-bandwidth-calculate.interval.millis")

(def MAGPIE-WORKER-CHILDOPTS "magpie.worker.childopts")
(def JAVA-LIBRARY-PATH "java.library.path")

(def MAGPIE-SUPERVISOR-GROUP "magpie.supervisor.group")
(def MAGPIE-SUPERVISOR-MAX-NET-BANDWIDTH "magpie.supervisor.max-net-bandwidth")

(def MAGPIE-CGROUP-ENABLE "magpie.cgroup.enable")
(def MAGPIE-CGROUP-PREFIX-DIR "magpie.cgroup.prefix.dir")
(def MAGPIE-CGROUP-NAME "magpie.cgroup.name")
(def MAGPIE-CGROUP-CPU-CORES "magpie.cgroup.cpu-cores")
(def MAGPIE-CGROUP-MEMORY "magpie.cgroup.memory")
(def MAGPIE-CGROUP-MEMSW "magpie.cgroup.memsw")

(def MAGPIE-METRICS-NAME ["com" "jd" "magpie"])
(def MAGPIE-SUPERVISOR-METRICS-NAME (into MAGPIE-METRICS-NAME ["supervisor"]))
(def MAGPIE-SUPERVISOR-HEARTBEAT-COUNTER-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["heartbeat-counter"]))
(def MAGPIE-SUPERVISOR-GET-MY-JOBS-TIMER-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["get-my-jobs-timer"]))
(def MAGPIE-SUPERVISOR-LAUNCH-JOB-TIMER-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["launch-job-timer"]))
(def MAGPIE-SUPERVISOR-PROCESS-JOB-TIMER-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["process-job-timer"]))
(def MAGPIE-SUPERVISOR-RX-NET-BANDWIDTH-GAUGE-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["rx-net-bandwidth-gauge"]))
(def MAGPIE-SUPERVISOR-TX-NET-BANDWIDTH-GAUGE-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["tx-net-bandwidth-gauge"]))
(def MAGPIE-SUPERVISOR-NET-BANDWIDTH-SCORE-GAUGE-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["net-bandwidth-score-gauge"]))
(def MAGPIE-SUPERVISOR-TOTAL-MEMORY-GAUGE-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["total-memory-gauge"]))
(def MAGPIE-SUPERVISOR-FREE-MEMORY-GAUGE-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["free-memory-gauge"]))
(def MAGPIE-SUPERVISOR-MEMORY-SCORE-GAUGE-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["memory-score-gauge"]))
(def MAGPIE-SUPERVISOR-TOTAL-SWAP-GAUGE-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["total-swap-gauge"]))
(def MAGPIE-SUPERVISOR-FREE-SWAP-GAUGE-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["free-swap-gauge"]))
(def MAGPIE-SUPERVISOR-LOAD-AVG-GAUGE-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["load-avg-gauge"]))
(def MAGPIE-SUPERVISOR-CPU-CORE-GAUGE-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["cpu-core-gauge"]))
(def MAGPIE-SUPERVISOR-CPU-SCORE-GAUGE-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["cpu-score-gauge"]))

(def MAGPIE-NIMBUS-METRICS-NAME (into MAGPIE-METRICS-NAME ["nimbus"]))
(def MAGPIE-NIMBUS-HEARTBEAT-COUNTER-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["heartbeat-counter"]))
(def MAGPIE-NIMBUS-TASKS-HEALTH-CHECK-TIMER-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["tasks-health-check-timer"]))
(def MAGPIE-NIMBUS-SUPERVISORS-HEALTH-CHECK-TIMER-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["supervisors-health-check-timer"]))
(def MAGPIE-NIMBUS-SUBMIT-TASK-TIMER-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["submit-task-timer"]))
(def MAGPIE-NIMBUS-OPERATE-TASK-TIMER-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["operate-task-timer"]))
(def MAGPIE-NIMBUS-PROCESS-ALL-TASKS-TIMER-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["process-all-tasks-timer"]))
(def MAGPIE-NIMBUS-PROCESS-DEAD-TASKS-TIMER-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["process-dead-tasks-timer"]))
(def MAGPIE-NIMBUS-TASKS-ASSIGNED-NUM-GAUGE-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["tasks-assigned-num-gauge"]))
(def MAGPIE-NIMBUS-TASKS-NO-SUPERVISOR-NUM-GAUGE-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["tasks-no-supervisor-num-gauge"]))
(def MAGPIE-NIMBUS-TASKS-LOST-SUPERVISOR-NUM-GAUGE-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["tasks-lost-supervisor-num-gauge"]))
(def MAGPIE-NIMBUS-TASKS-ERROR-SUPERVISOR-NUM-GAUGE-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["tasks-error-supervisor-num-gauge"]))
