(ns com.jd.magpie.bootstrap)

(use 'clojure.set) 

(def NIMBUS-THRIFT-PORT "nimbus.thrift.port")
(def MAGPIE-ZOOKEEPER-SERVERS "magpie.zookeeper.servers")
(def MAGPIE-ZOOKEEPER-PORT "magpie.zookeeper.port")
(def MAGPIE-ZOOKEEPER-ROOT "magpie.zookeeper.root")
(def MAGPIE-ZOOKEEPER-CONNECTION-TIMEOUT "magpie.zookeeper.connection.timeout.millis")
(def MAGPIE-ZOOKEEPER-SESSION-TIMEOUT "magpie.zookeeper.session.timeout.millis")
(def MAGPIE-ZOOKEEPER-RETRY-INTERVAL "magpie.zookeeper.retry.interval.millis")
(def MAGPIE-ZOOKEEPER-RETRY-TIMES "magpie.zookeeper.retry.times")
(def MAGPIE-ZOOKEEPER-RETRY-INTERVAL-CEILING "magpie.zookeeper.retry.intervalceiling.millis")
(def MAGPIE-ZOOKEEPER-AUTH-SCHEME "magpie.zookeeper.auth.scheme")
(def MAGPIE-ZOOKEEPER-AUTH-PAYLOAD "magpie.zookeeper.auth.payload")

(def MAGPIE-FLOOR-SCORE "magpie.floor.score")
(def MAGPIE-JARS-DIR "magpie.jars.dir")
(def MAGPIE-PIDS-DIR "magpie.pids.dir")
(def MAGPIE-LOGS-DIR "magpie.logs.dir")
(def MAGPIE-HEARTBEAT-INTERVAL "magpie.heartbeat.interval.millis")
(def MAGPIE-SCHEDULE-INTERVAL "magpie.schedule.interval.millis")
(def MAGPIE-SCHEDULE-TIMEOUT "magpie.schedule.timeout.millis")
(def MAGPIE-SCHEDULE-LAUNCHWORKER-TIMEOUT "magpie.schedule.launchworker.timeout.millis")
(def MAGPIE-NET-BANDWIDTH-CALCULATE-INTERVAL "magpie.net-bandwidth-calculate.interval.millis")

(def MAGPIE-WORKER-CHILDOPTS "magpie.worker.childopts")
(def JAVA-LIBRARY-PATH "java.library.path")

(def MAGPIE-SUPERVISOR-GROUP "magpie.supervisor.group")
(def MAGPIE-SUPERVISOR-MAX-NET-BANDWIDTH "magpie.supervisor.max-net-bandwidth")

(def MAGPIE-CGROUP-ENABLE "magpie.cgroup.enable")
(def MAGPIE-CGROUP-NAME "magpie.cgroup.name")
(def MAGPIE-CGROUP-CPU-CORES "magpie.cgroup.cpu-cores")
(def MAGPIE-CGROUP-MEMORY "magpie.cgroup.memory")
(def MAGPIE-CGROUP-MEMSW "magpie.cgroup.memsw")

(def MAGPIE-METRICS-NAME ["com" "jd" "magpie"])
(def MAGPIE-SUPERVISOR-METRICS-NAME (into MAGPIE-METRICS-NAME ["supervisor"]))
(def MAGPIE-SUPERVISOR-HEARTBEAT-COUNTER-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["heartbeat-counter"]))
(def MAGPIE-SUPERVISOR-GET-MY-JOBS-TIMER-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["get-my-jobs-timer"]))
(def MAGPIE-SUPERVISOR-LAUNCH-JOB-TIMER-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["launch-job-timer"]))
(def MAGPIE-SUPERVISOR-PROCESS-JOB-TIMER-METRICS-NAME (into MAGPIE-SUPERVISOR-METRICS-NAME ["process-job-timer"]))
(def MAGPIE-NIMBUS-METRICS-NAME (into MAGPIE-METRICS-NAME ["nimbus"]))
(def MAGPIE-NIMBUS-HEARTBEAT-COUNTER-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["heartbeat-counter"]))
(def MAGPIE-NIMBUS-HEALTH-CHECK-TIMER-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["health-check-timer"]))
(def MAGPIE-NIMBUS-SUBMIT-TASK-TIMER-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["submit-task-timer"]))
(def MAGPIE-NIMBUS-OPERATE-TASK-TIMER-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["operate-task-timer"]))
(def MAGPIE-NIMBUS-PROCESS-ALL-TASKS-TIMER-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["process-all-tasks-timer"]))
(def MAGPIE-NIMBUS-PROCESS-DEAD-TASKS-TIMER-METRICS-NAME (into MAGPIE-NIMBUS-METRICS-NAME ["process-dead-tasks-timer"]))
